/* ============================================================
   PEARL JAM BAND SPRITES — 3 frames each, beat'em up style
   Frames cycle: A → B → C → A → B → C... at ~5 FPS
   Each sprite is 28×32 pixel grid. '.' = transparent.
   Per-member palette maps single chars to colors.
============================================================ */

window.PJ_MEMBERS = [
  /* ───────────────────── EDDIE VEDDER ───────────────────── */
  {
    id: "eddie",
    name: "Eddie Vedder",
    role: "Vocal · Letras",
    photo: "media/eddie.jpg",
    photoPos: "center 18%",
    initials: "EV",
    bio: {
      born: "23 dez 1964 · Evanston, IL",
      since: "1990 · Pearl Jam",
      also: "Solo (2007–), Into the Wild OST",
      voice: "Barítono · contralto invertido"
    },
    text: "A voz que define o som da banda. Surfa, milita, sussurra um <em>“yeah”</em> que vira hino. Quando a letra acaba, improvisa frases inteiras que jamais saem do disco mas todo mundo grava na cabeça.",
    tags: ["Surf", "Ativismo", "Whistle solo"],
    palette: {
      h:"#3a2415", H:"#5c3a1e",
      s:"#e8c4a0", S:"#c89878",
      e:"#1a1a1a", m:"#8a6a4a",
      t:"#1a1a1a", T:"#2a2a2a",
      p:"#2c4258", P:"#1a2d44",
      b:"#0a0a0a",
      c:"#b8b3a4", C:"#5a5042",
      r:"#c1272d", w:"#f5f1e8"
    },
    // Frame A — mic raised TO MOUTH, screaming
    frameA: [
      "..........hhhhhh............",
      ".........HHHHHHHH...........",
      "........HHHHHHHHHH..........",
      ".......HHhhhhhhhhh..........",
      "......HHhhhhhhhhhh..........",
      "......hhhhhhhhhhhh..........",
      "......hhsssssssshh..........",
      "......hssssssssshh..........",
      "......hsseeSseesshh.........",
      "......hsssssssssshh.........",
      ".......sssSmsSsss.h.........",
      ".......ssSmmmmSss.hh........",
      "........SmmmmmmS..hh........",
      ".........mmmmmm...CC........",
      ".........ssssss....ch.......",
      "........rttttttr...ch.......",
      "......ssrttttttr...c........",
      ".....sssrttttttr..ss........",
      "....ssss.tttttt.ssssc.......",
      "....ssss.tttttt.sssccc......",
      ".....sss.tttttt.sss.c.......",
      "......s..tttttt..s..c.......",
      ".........tTTTTt.....c.......",
      ".........pppppp.............",
      ".........pPPPPp.............",
      ".........pPPPPp.............",
      ".........pP..Pp.............",
      ".........pP..Pp.............",
      ".........pP..Pp.............",
      ".........bb..bb.............",
      ".........bb..bb.............",
      "........bbbbbbbb............"
    ],
    // Frame B — mic at chest level (idle, holding strap)
    frameB: [
      "..........hhhhhh............",
      ".........HHHHHHHH...........",
      "........HHHHHHHHHH..........",
      ".......HHhhhhhhhhh..........",
      "......HHhhhhhhhhhh..........",
      "......hhhhhhhhhhhh..........",
      "......hhsssssssshh..........",
      "......hssssssssshh..........",
      "......hsseeSseesshh.........",
      "......hsssssssssshh.........",
      ".......sssSmsSsss.h.........",
      ".......ssSmmmmSss.hh........",
      "........SmmmmmmS..hh........",
      ".........mmmmmm....h........",
      ".........ssssss....hh.......",
      "........rttttttr....h.......",
      "......ssrttttttr...sC.......",
      ".....sssrttttttr..ssC.......",
      "....ssss.tttttt.ssssc.......",
      "....ssss.tttttt.sssccc......",
      ".....sss.tttttt.sss.c.......",
      "......s..tttttt..s..c.......",
      ".........tTTTTt.....c.......",
      ".........pppppp.............",
      ".........pPPPPp.............",
      ".........pPPPPp.............",
      ".........pP..Pp.............",
      ".........pP..Pp.............",
      ".........pP..Pp.............",
      ".........bb..bb.............",
      ".........bb..bb.............",
      "........bbbbbbbb............"
    ],
    // Frame C — free arm thrown UP, fist clenched (preacher pose)
    frameC: [
      "..........hhhhhh............",
      ".........HHHHHHHH...........",
      "........HHHHHHHHHH..........",
      ".......HHhhhhhhhhh..........",
      "......HHhhhhhhhhhh..........",
      "......hhhhhhhhhhhh..........",
      "......hhsssssssshh..........",
      "......hssssssssshh..........",
      "......hsseeSseesshh.........",
      "......hsssssssssshh.........",
      ".......sssSmsSsss.h.........",
      ".......ssSmmmmSss.hh........",
      "........SmmmmmmS..hh........",
      ".........mmmmmm....h........",
      ".........ssssss....hh.......",
      "........rttttttr....h.......",
      "......ssrttttttr...s........",
      ".....sssrttttttr..ss........",
      "....ssss.tttttt.ssssc.CC....",
      "....ssss.tttttt.sssccccc....",
      ".....sss.tttttt.sss.c.......",
      "......s..tttttt..s..cc......",
      ".........tTTTTt.....c.......",
      ".........pppppp.............",
      ".........pPPPPp.............",
      ".........pPPPPp.............",
      ".........pP..Pp.............",
      ".........pP..Pp.............",
      ".........pP..Pp.............",
      ".........bb..bb.............",
      ".........bb..bb.............",
      "........bbbbbbbb............"
    ]
  },

  /* ───────────────────── STONE GOSSARD ───────────────────── */
  {
    id: "stone",
    name: "Stone Gossard",
    role: "Guitarra rítmica",
    photo: "media/stone.jpg",
    photoPos: "center 12%",
    initials: "SG",
    bio: {
      born: "20 jul 1966 · Seattle, WA",
      since: "1990 · co-fundador",
      also: "Green River, Mother Love Bone, Brad",
      sig: "Riff de “Alive” · acordes abertos"
    },
    text: "Arquiteto rítmico. Dissonância controlada, voicings abertos, riffs angulares. Quem amarra a engrenagem no chão quando o Mike sai voando.",
    tags: ["Les Paul", "Riff master", "Brad"],
    palette: {
      h:"#3a2818", H:"#5e4530",
      s:"#e8c8a4", S:"#c89878",
      e:"#1a1a1a", f:"#3a3a3a",
      t:"#1a1a1a", T:"#2a2a2a",
      p:"#1f1f1f", P:"#0f0f0f",
      b:"#0a0a0a",
      g:"#d4a347", G:"#8a6a23",
      n:"#3a2415", N:"#1a0e05",
      w:"#f5f1e8", r:"#7a1a1d"
    },
    // Frame A — pick hand UP (mid-downstroke begins)
    frameA: [
      "..........hhhhhh............",
      ".........HHHHHHH............",
      "........HHhhhhhhh...........",
      ".......HHhhhhhhhh...........",
      ".......hhhhhhhhhh...........",
      "........sssssss.............",
      "........sssssss.............",
      "........ffefeff.............",
      "........fSSSSSf.............",
      ".........sssss..............",
      "........ssssss..............",
      ".......rttttttr.............",
      "......sttttttts.............",
      "......stttttttsg............",
      ".....ssttttttssgg...........",
      ".....ssttttttssgggn.........",
      "....sssttttttsssggnn........",
      "....sss.tttt.sssgggssN......",
      "....sss.tttt.sssgggssnN.....",
      "....ssss....sssgggggnnN.....",
      ".....s..pppp..s.gggg.nN.....",
      "........ppppp...gggg..N.....",
      "........pPPPp....gg.........",
      "........pPPPp...............",
      "........pPPPp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........bb.bb...............",
      "........bb.bb...............",
      ".......bbbbbbb..............",
      "............................"
    ],
    // Frame B — pick hand mid-strum (across body)
    frameB: [
      "..........hhhhhh............",
      ".........HHHHHHH............",
      "........HHhhhhhhh...........",
      ".......HHhhhhhhhh...........",
      ".......hhhhhhhhhh...........",
      "........sssssss.............",
      "........sssssss.............",
      "........ffefeff.............",
      "........fSSSSSf.............",
      ".........sssss..............",
      "........ssssss..............",
      ".......rttttttr.............",
      "......sttttttts.............",
      "......stttttttsg............",
      ".....ssttttttssgg...........",
      ".....ssttttttssgggn.........",
      "....sssttttttsssggnn........",
      "....sss.tttt.sssggggnN......",
      "....sss.tttt.sssggggnnN.....",
      "....ssss....sssgggggnnN.....",
      ".....s..pppp..s.gggg.nN.....",
      "........ppppp...gggg..N.....",
      "........pPPPp....gg.........",
      "........pPPPp...............",
      "........pPPPp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........bb.bb...............",
      "........bb.bb...............",
      ".......bbbbbbb..............",
      "............................"
    ],
    // Frame C — pick hand DOWN (end of downstroke / windmill bottom)
    frameC: [
      "..........hhhhhh............",
      ".........HHHHHHH............",
      "........HHhhhhhhh...........",
      ".......HHhhhhhhhh...........",
      ".......hhhhhhhhhh...........",
      "........sssssss.............",
      "........sssssss.............",
      "........ffefeff.............",
      "........fSSSSSf.............",
      ".........sssss..............",
      "........ssssss..............",
      ".......rttttttr.............",
      "......sttttttts.............",
      "......stttttttsg............",
      ".....ssttttttssgg...........",
      ".....ssttttttssgggn.........",
      "....sssttttttsssggnn........",
      "....sss.tttt.sssggggnN......",
      "....sss.tttt.sssggggnnN.....",
      "....ssss....sssgggggnnN.....",
      ".....s..pppp..s.ssgg.nN.....",
      "........ppppp...ssgg..N.....",
      "........pPPPp...ssg.........",
      "........pPPPp...............",
      "........pPPPp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........bb.bb...............",
      "........bb.bb...............",
      ".......bbbbbbb..............",
      "............................"
    ]
  },

  /* ───────────────────── JEFF AMENT ───────────────────── */
  {
    id: "jeff",
    name: "Jeff Ament",
    role: "Baixo · Capas",
    photo: "media/jeff.jpg",
    photoPos: "center 15%",
    initials: "JA",
    bio: {
      born: "10 mar 1963 · Big Sandy, MT",
      since: "1990 · co-fundador",
      also: "Green River, MLB, Tres Mts.",
      sig: "Stick bass · linhas melódicas"
    },
    text: "Designer das capas, do logo, da identidade visual inteira. Anda de skate, joga basquete, escreveu “Jeremy” e “Nothingman”. Veste boné porque é Montana, não porque é estilo.",
    tags: ["Beanie", "Skate", "Stick bass"],
    palette: {
      H:"#1a1a1a", h:"#0a0a0a",
      s:"#e8c4a0", S:"#c89878",
      e:"#1a1a1a",
      t:"#3a3a3a", T:"#1a1a1a",
      w:"#f5f1e8",
      p:"#2a2a2a", P:"#1a1a1a",
      b:"#0a0a0a",
      n:"#c89a5c", N:"#8a6a3a",
      g:"#3a2415", G:"#1f1408",
      r:"#c1272d"
    },
    // Frame A — pluck hand DOWN, fret hand high on neck
    frameA: [
      "............................",
      ".........HHHHHHH............",
      "........HHHHHHHHH...........",
      "........HhhhhhhhH...........",
      "........HHHHHHHH............",
      ".........ssssss.............",
      ".........ssssss.............",
      ".........seesee.............",
      ".........ssSsss.............",
      "..........smms..............",
      "..........smms..............",
      "........rtttttr.............",
      ".......rttwwwwwttr..........",
      "......sttwwTwwwwtts.........",
      "......sttwwwwTwwtts.........",
      ".....ssttwwwwwwwttssn.......",
      "....sssstttttttssssnN.......",
      "....sss.tttttttssssnN.......",
      "....sss.tttttttssssnNgg.....",
      "....ssss......sssNNgggg.....",
      ".....s..pppppp..s.Nggggg....",
      "........ppppppp...gGGggg....",
      "........pPPPPPp...ggggg.....",
      "........pPPPPPp....gg.......",
      "........pPPPPPp.............",
      "........pPP.PPp.............",
      "........pPP.PPp.............",
      "........pPP.PPp.............",
      "........bbb.bbb.............",
      "........bbb.bbb.............",
      ".......bbbbbbbbb............",
      "............................"
    ],
    // Frame B — both hands centered on bass
    frameB: [
      "............................",
      ".........HHHHHHH............",
      "........HHHHHHHHH...........",
      "........HhhhhhhhH...........",
      "........HHHHHHHH............",
      ".........ssssss.............",
      ".........ssssss.............",
      ".........seesee.............",
      ".........ssSsss.............",
      "..........smms..............",
      "..........smms..............",
      "........rtttttr.............",
      ".......rttwwwwwttr..........",
      "......sttwwTwwwwtts.........",
      "......sttwwwwTwwtts.........",
      ".....ssttwwwwwwwttssn.......",
      "....sssstttttttssssnN.......",
      "....sss.ttttttt.sssnN.......",
      "....sss.ttttttt.sssnNgg.....",
      "....ssss......sssNNgggg.....",
      ".....s..pppppp..s.Nggggg....",
      "........ppppppp...gGGggg....",
      "........pPPPPPp...ggggg.....",
      "........pPPPPPp....gg.......",
      "........pPPPPPp.............",
      "........pPP.PPp.............",
      "........pPP.PPp.............",
      "........pPP.PPp.............",
      "........bbb.bbb.............",
      "........bbb.bbb.............",
      ".......bbbbbbbbb............",
      "............................"
    ],
    // Frame C — JUMP! both legs bent, body lifted
    frameC: [
      "............................",
      ".........HHHHHHH............",
      "........HHHHHHHHH...........",
      "........HhhhhhhhH...........",
      "........HHHHHHHH............",
      ".........ssssss.............",
      ".........ssssss.............",
      ".........seesee.............",
      ".........ssSsss.............",
      "..........smms..............",
      "..........smms..............",
      "........rtttttr.............",
      ".......rttwwwwwttr..........",
      "......sttwwTwwwwtts.........",
      "......sttwwwwTwwtts.........",
      ".....ssttwwwwwwwttssn.......",
      "....sssstttttttssssnN.......",
      "....sss.ttttttt.sssnN.......",
      "....sss.ttttttt.sssnNgg.....",
      "....ssss......sssNNgggg.....",
      ".....s..pppppp..s.Nggggg....",
      "........ppppppss..gGGggg....",
      "........pPPPPPss..ggggg.....",
      "........pPPPPPp....gg.......",
      "........pPPPPPp.............",
      "........pPP.PPp.............",
      "........pPP.PPp.............",
      "........pPP.PPp.............",
      "........bbb.bbb.............",
      "........bbb.bbb.............",
      ".......bbbbbbbbb............",
      "............................"
    ]
  },

  /* ───────────────────── MIKE McCREADY ───────────────────── */
  {
    id: "mike",
    name: "Mike McCready",
    role: "Guitarra solo",
    photo: "media/mike.jpg",
    photoPos: "center 20%",
    initials: "MM",
    bio: {
      born: "5 abr 1966 · Pensacola, FL",
      since: "1990 · Pearl Jam",
      also: "Mad Season, Temple of the Dog",
      sig: "Strat amassada · solo de Alive"
    },
    text: "O solo. Stratocaster amassada de tanto chão. Fraseado bluesy, Hendrix encontrando Stevie Ray Vaughan numa esquina de Seattle. Aprendeu Ace Frehley antes de aprender Kenny Burrell.",
    tags: ["Strat", "Hendrix", "Mad Season"],
    palette: {
      H:"#f0e8d4", h:"#c8c0a8",
      s:"#f0c9a8", S:"#c89878",
      e:"#1a1a1a",
      t:"#1a1a1a", T:"#0a0a0a",
      p:"#1a1a1a", P:"#0a0a0a",
      b:"#0a0a0a",
      g:"#0a0a0a", G:"#1a1a1a",
      w:"#f0ebd4", W:"#c8c0a8",
      n:"#d4a767", N:"#8a6a3a",
      r:"#7a1a1d"
    },
    // Frame A — fret hand HIGH on neck (lead bend), arched back
    frameA: [
      ".........HHHHHHH............",
      "........HHHHhHHHH...........",
      ".......HHHHhhHHHHH..........",
      "......HHhHHhHHHhHH..........",
      ".....HHhhhhhhhhhhH..........",
      ".....hhhhhhhhhhhh...........",
      "......hsssssssssh...........",
      "......hssssssssh............",
      ".......seeSseesh............",
      ".......sssssssss............",
      ".......sSmmmmmSs............",
      "........ssmmmss.............",
      "........rttttr..............",
      ".......rttttttr.............",
      "......stttttttts............",
      ".....sstttttttts............",
      "....sssttttttttss...........",
      "....sss.tttttt..ss..........",
      "....sss.tttttt..ssss........",
      "....ssss.....nNNNNssss......",
      ".....s..pppppwwWwwppss......",
      "........ppppwwgggwwpp.......",
      "........pPPpwggGggwpp.......",
      "........pPPpwwgggwwpp.......",
      "........pPPp.wwwww..........",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........bb.bb...............",
      "........bb.bb...............",
      ".......bbbbbbb..............",
      "............................"
    ],
    // Frame B — neutral playing pose
    frameB: [
      ".........HHHHHHH............",
      "........HHHHhHHHH...........",
      ".......HHHHhhHHHHH..........",
      "......HHhHHhHHHhHH..........",
      ".....HHhhhhhhhhhhH..........",
      ".....hhhhhhhhhhhh...........",
      "......hsssssssssh...........",
      "......hssssssssh............",
      ".......seeSseesh............",
      ".......sssssssss............",
      ".......sSmmmmmSs............",
      "........ssmmmss.............",
      "........rttttr..............",
      ".......rttttttr.............",
      "......stttttttts............",
      ".....sstttttttts............",
      "....sssttttttttss...........",
      "....sss.tttttt..ss..........",
      "....sss.tttttt..ss..........",
      "....ssss.....nNNNNnsss......",
      ".....s..pppppwwWwwppss......",
      "........ppppwwgggwwpp.......",
      "........pPPpwggGggwpp.......",
      "........pPPpwwgggwwpp.......",
      "........pPPp.wwwww..........",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........bb.bb...............",
      "........bb.bb...............",
      ".......bbbbbbb..............",
      "............................"
    ],
    // Frame C — leg kicked OUT, leaning back wild
    frameC: [
      ".........HHHHHHH............",
      "........HHHHhHHHH...........",
      ".......HHHHhhHHHHH..........",
      "......HHhHHhHHHhHH..........",
      ".....HHhhhhhhhhhhH..........",
      ".....hhhhhhhhhhhh...........",
      "......hsssssssssh...........",
      "......hssssssssh............",
      ".......seeSseesh............",
      ".......sssssssss............",
      ".......sSmmmmmSs............",
      "........ssmmmss.............",
      "........rttttr..............",
      ".......rttttttr.............",
      "......stttttttts............",
      ".....sstttttttts............",
      "....sssttttttttss...........",
      "....sss.tttttt..ss..........",
      "....sss.tttttt..ss..........",
      "....ssss.....nNNNNnsss......",
      ".....s..pppppwwWwwppss......",
      "........ppppwwssgwwpp.......",
      "........pPPpwgssggwpp.......",
      "........pPPpwwgggwwpp.......",
      "........pPPp.wwwww..........",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........pP.Pp...............",
      "........bb.bb...............",
      "........bb.bb...............",
      ".......bbbbbbb..............",
      "............................"
    ]
  },

  /* ───────────────────── MATT CAMERON ───────────────────── */
  {
    id: "matt",
    name: "Matt Cameron",
    role: "Bateria",
    photo: "media/matt.jpg",
    photoPos: "center 25%",
    initials: "MC",
    bio: {
      born: "28 nov 1962 · San Diego, CA",
      since: "1998 · Pearl Jam",
      also: "Soundgarden, Skin Yard, Wellwater",
      sig: "Compassos compostos em rock direto"
    },
    text: "Bateria do Soundgarden virou bateria do Pearl Jam. Polirritmia disfarçada de groove. Compositor — escreveu “You Are”, “Unthought Known”, parte do <em>Backspacer</em>.",
    tags: ["Soundgarden", "5/4", "Hi-hat"],
    palette: {
      h:"#3a2818", H:"#5e4530",
      s:"#e8c4a0", S:"#c89878",
      e:"#1a1a1a", m:"#7a4a2a",
      t:"#1a1a1a", T:"#2a2a2a",
      k:"#c89a5c", K:"#8a6a3a",
      c:"#d4a347", C:"#8a6a23",
      d:"#7a1a1d", D:"#4a0f12",
      w:"#f0ebd4", W:"#c8c0a8",
      b:"#0a0a0a"
    },
    // Frame A — LEFT stick striking down, RIGHT stick up high
    frameA: [
      "..cccccc..........cccccc....",
      ".cCCCCCCc........cCCCCCCc...",
      "..cccccc..........cccccc....",
      "....C.K...............C.....",
      "....C.K....hhhhhh.....C.....",
      "....CK....HHHHHHHH....C.....",
      "....CK...HHhhhhhhh....C.....",
      "....K....hhhhhhhhh..........",
      "..........sssssss...........",
      "..........seeSees...........",
      "..........smmmmmm...........",
      "...........mmmmmm...........",
      "..K........tttttt.........k.",
      "..KK.....rtttttttr.......kk.",
      "...KK..sstttttttts......kk..",
      "....KK.sstttttttts....kk....",
      ".....K..sttttttttss..kk.....",
      ".......ssttttttttssssk......",
      "......sss..tttt..sssk..k....",
      ".....wwwwwddddddwwwww.kk....",
      "....wWWWWdDDDDDDdWWWWw......",
      "....wWWWWdDDDDDDdWWWWw......",
      "....wWWWWdDDDDDDdWWWWw......",
      ".....wwwwdDDDDDDdwwww.......",
      "........bdDDDDDDdb..........",
      "........bdDDDDDDdb..........",
      "........bdDDDDDDdb..........",
      "........bbDDDDDDbb..........",
      ".......bbbDDDDDDbbb.........",
      "......bbbbbbbbbbbbbb........",
      "............................",
      "............................"
    ],
    // Frame B — both sticks DOWN on drums (impact!)
    frameB: [
      "..cccccc..........cccccc....",
      ".cCCCCCCc........cCCCCCCc...",
      "..cccccc..........cccccc....",
      "....C.................C.....",
      "....C......hhhhhh.....C.....",
      "....C.....HHHHHHHH....C.....",
      "....C....HHhhhhhhh....C.....",
      ".........hhhhhhhhh..........",
      "..........sssssss...........",
      "..........seeSees...........",
      "..........smmmmmm...........",
      "...........mmmmmm...........",
      "..K........tttttt.........k.",
      "..KK.....rtttttttr.......kk.",
      "...KK..sstttttttts......kk..",
      "....KK.sstttttttts....kk....",
      ".....KKssttttttttss..kk.....",
      "......sssttttttttssssk......",
      "......sss..tttt..sssk.......",
      ".....wwwwwddddddwwwww.......",
      "....wWWWWdDDDDDDdWWWWw......",
      "....wWWWWdDDDDDDdWWWWw......",
      "....wWWWWdDDDDDDdWWWWw......",
      ".....wwwwdDDDDDDdwwww.......",
      "........bdDDDDDDdb..........",
      "........bdDDDDDDdb..........",
      "........bdDDDDDDdb..........",
      "........bbDDDDDDbb..........",
      ".......bbbDDDDDDbbb.........",
      "......bbbbbbbbbbbbbb........",
      "............................",
      "............................"
    ],
    // Frame C — LEFT stick up high, RIGHT stick striking down
    frameC: [
      "..cccccc..........cccccc....",
      ".cCCCCCCc........cCCCCCCc...",
      "..cccccc..........cccccc....",
      "....C................kC.....",
      "....C......hhhhhh....kC.....",
      "....C.....HHHHHHHH....k.....",
      "....C....HHhhhhhhh....k.....",
      ".........hhhhhhhhh.....k....",
      "..........sssssss...........",
      "..........seeSees...........",
      "..........smmmmmm...........",
      "...........mmmmmm...........",
      "..K........tttttt.........k.",
      "..KK.....rtttttttr........k.",
      "...KK..sstttttttts......k...",
      "....KK.sstttttttts....kk....",
      ".....KKssttttttttss..kk.....",
      "......sssttttttttssss.......",
      ".....Ksss..tttt..sssk.......",
      ".....KKwwwddddddwwwww.......",
      "....wWWWWdDDDDDDdWWWWw......",
      "....wWWWWdDDDDDDdWWWWw......",
      "....wWWWWdDDDDDDdWWWWw......",
      ".....wwwwdDDDDDDdwwww.......",
      "........bdDDDDDDdb..........",
      "........bdDDDDDDdb..........",
      "........bdDDDDDDdb..........",
      "........bbDDDDDDbb..........",
      ".......bbbDDDDDDbbb.........",
      "......bbbbbbbbbbbbbb........",
      "............................",
      "............................"
    ]
  },

  /* ───────────────────── BOOM GASPAR ───────────────────── */
  {
    id: "boom",
    name: "Boom Gaspar",
    role: "Teclados · Hammond",
    photo: "media/boom.jpg",
    photoPos: "center 22%",
    initials: "BG",
    bio: {
      born: "1953 · Havaí, EUA",
      since: "2002 · auxiliar de turnê",
      also: "B3 Brothers, amigo de surfe do Eddie",
      sig: "Hammond B3 em “Love Boat Captain”"
    },
    text: "O som que ninguém percebe que sustenta o som. Hammond B3 no fundo, almofada harmônica que faz “Love Boat Captain” respirar. Conheceu o Eddie surfando no Havaí — chegou na banda pela porta do oceano.",
    tags: ["Hammond B3", "Havaí", "Riot Act"],
    palette: {
      h:"#1a2540", H:"#2a3a5a",
      s:"#c89878", S:"#a87a5a",
      e:"#0a0a0a", E:"#2a2a2a",
      m:"#f0ebd4", M:"#c8c0a8",
      t:"#1a1a1a", T:"#0a0a0a",
      b:"#5a3a20", B:"#3a2415",
      w:"#f0ebd4", K:"#0a0a0a"
    },
    // Frame A — left hand striking LEFT keys (bass notes)
    frameA: [
      "............................",
      "............................",
      ".......hhhhhhhhhhhh.........",
      "......hhhhhhhhhhhhh.........",
      ".....hhhhhhhhhhhhhh.........",
      "......hhhhhhhhhhhhh.........",
      "........ssssssssss..........",
      ".......eeeesseeeee..........",
      "......eEEEsseEEEEe..........",
      ".......eeeeeeeeeee..........",
      "........ssssssssss..........",
      "........smmmmmmmms..........",
      "........mmmmmmmmmm..........",
      ".........mmmmmmmm...........",
      "..........mmmmmm............",
      "..........ttttt.............",
      ".......tttttttttt...........",
      "......ttttttttttts..........",
      ".....ttttttttttttts.........",
      ".....tttttttttttttts........",
      "....ttttttttttttttts........",
      "....tttsstttttttttts........",
      "....bBBssBBBBBBBBBBb........",
      "....bwwwwwwwwwwwwwwb........",
      "....bKwwKwKwsswKwKwb........",
      "....bwwwwwwsssswwwwb........",
      "....bKwwKwKwsswKwKwb........",
      "....bBBBBBBBBBBBBBBb........",
      ".....bBBBBBBBBBBBBb.........",
      "......BBBBBBBBBBBB..........",
      "............................",
      "............................"
    ],
    // Frame B — both hands centered on keys
    frameB: [
      "............................",
      "............................",
      ".......hhhhhhhhhhhh.........",
      "......hhhhhhhhhhhhh.........",
      ".....hhhhhhhhhhhhhh.........",
      "......hhhhhhhhhhhhh.........",
      "........ssssssssss..........",
      ".......eeeesseeeee..........",
      "......eEEEsseEEEEe..........",
      ".......eeeeeeeeeee..........",
      "........ssssssssss..........",
      "........smmmmmmmms..........",
      "........mmmmmmmmmm..........",
      ".........mmmmmmmm...........",
      "..........mmmmmm............",
      "..........ttttt.............",
      ".......tttttttttt...........",
      "......ttttttttttts..........",
      ".....ttttttttttttts.........",
      ".....tttttttttttttts........",
      "....ttttttttttttttts........",
      "....ttttttttttttttts........",
      "....bBBBBBBBBBBBBBBb........",
      "....bwwwwwwwwwwwwwwb........",
      "....bKwwKwKwsswKwKwb........",
      "....bwwwwwwsssswwwwb........",
      "....bKwwKwKwsswKwKwb........",
      "....bBBBBBBBBBBBBBBb........",
      ".....bBBBBBBBBBBBBb.........",
      "......BBBBBBBBBBBB..........",
      "............................",
      "............................"
    ],
    // Frame C — right hand striking RIGHT keys (lead/high notes), pointing
    frameC: [
      "............................",
      "............................",
      ".......hhhhhhhhhhhh.........",
      "......hhhhhhhhhhhhh.........",
      ".....hhhhhhhhhhhhhh.........",
      "......hhhhhhhhhhhhh.........",
      "........ssssssssss..........",
      ".......eeeesseeeee..........",
      "......eEEEsseEEEEe..........",
      ".......eeeeeeeeeee..........",
      "........ssssssssss..........",
      "........smmmmmmmms..........",
      "........mmmmmmmmmm..........",
      ".........mmmmmmmm...........",
      "..........mmmmmm............",
      "..........ttttt.............",
      ".......tttttttttt...........",
      "......ttttttttttts..........",
      ".....ttttttttttttts.........",
      ".....tttttttttttttts........",
      "....ttttttttttttttts........",
      "....ttttttttttttttss........",
      "....bBBBBBBBBBBBBBss........",
      "....bwwwwwwwwwwwwwwb........",
      "....bKwwKwKwsswKwKwb........",
      "....bwwwwwwsssswwwwb........",
      "....bKwwKwKwsswKwKwb........",
      "....bBBBBBBBBBBBBBBb........",
      ".....bBBBBBBBBBBBBb.........",
      "......BBBBBBBBBBBB..........",
      "............................",
      "............................"
    ]
  }
];
